name: Provision EC2 Instance

on:
  # Permite a execução manual a partir da interface do GitHub
  workflow_dispatch:
    inputs:
      instance_name: 
        description: 'Nome da instância EC2 a ser criada'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TF_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      # - name: Extract Instance Name from Issue
      #   run: |
      #     export INSTANCE_NAME=$(echo "${{ github.event.issue.title }}")
      #     echo "Instance Name: $INSTANCE_NAME"
      #     echo "INSTANCE_NAME=$INSTANCE_NAME" >> $GITHUB_ENV          

      - name: Run Terraform for EC2
        run: |
          terraform apply -auto-approve \
            -var="instance_name=${{ github.event.inputs.instance_name }}" \
            -var="private_key_path=~/.ssh/id_rsa"